--- 
abstract: A simple module for managing versioned file names
author: 
  - Stevan Little <stevan.little@iinteractive.com>
build_requires: 
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Path-Class-Versioned
no_index: 
  directory: 
    - inc
    - t
requires: 
  List::Util: 0
  Moose: 0.44
  MooseX::Params::Validate: 0.05
  MooseX::Types::Path::Class: 0.04
  Path::Class: 0
  overload: 0
tests: t/*.t
version: 0.01
